version: '3'
services:
  polls-app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /opt/django-tutorial-app/mysite
    ports:
      - 8000:8000
    depends_on:
      - polls-db
  polls-db:
    image: postgres:9.6.19-alpine
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=mydatabaseuser
      - POSTGRES_PASSWORD=mypassword